# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kfzkYauW6Ki-wou35umk1Y8NdsTQUFgV
"""

productos = {}

def menu():
    while True:
        print("\nMENU")
        print("1 - agregar producto")
        print("2 - eliminar producto")
        print("3 - actualizar cantidad y precio")
        print("4 - mostrar productos")
        print("5 - mostrar productos por agotarse")
        print("6 - salir")
        opcion = input("seleccione una opcion").strip()

        if opcion == '1':
            nombre = input("nombre").strip()
            if nombre in productos:
                print("el producto ya existe")
            else:
                cantidad = int(input("cantidad"))
                precio = float(input("precio"))
                productos[nombre] = {'cantidad': cantidad, 'precio': precio}
                print(f"producto'{nombre}' agregado")
        elif opcion == '2':
            nombre = input("nombre").strip()
            if productos.pop(nombre, None):
                print(f"Producto'{nombre}' eliminado")
            else:
                print("el producto no existe")
        elif opcion == '3':
            nombre = input("nombre").strip()
            if nombre in productos:
                productos[nombre]['cantidad'] = int(input("nueva cantidad"))
                productos[nombre]['precio'] = float(input("nuevo precio"))
                print(f"Producto'{nombre}' actualizado")
            else:
                print("El producto no existe.")
        elif opcion == '4':
            print("productos")
            for nombre, info in productos.items():
                print(f"{nombre}: cantidad {info['cantidad']}, precio ${info['precio']:.2f}")
        elif opcion == '5':
            print("productos por agotarse")
            agotados = [f"{n}: cantidad {d['cantidad']}, precio ${d['precio']:.2f}"
                        for n, d in productos.items() if d['cantidad'] < 5]
            print("\n".join(agotados) if agotados else "no hay productos por agotarse")
        elif opcion == '6':
            break
        else:
            print("Opción no válida.")

menu()